### PR TITLE
use spring_client

### PR DESCRIPTION
**Pull request by grosser**
as suggested by @jonleighton 
/cc @rafaelfranca

### CODE REVIEW

**Comment by grosser** [comment]
can you do a release after merging this ?

**Comment by rafaelfranca** [comment]
@grosser could you please send your rubygems emails so I can add you as gem owner?

**Comment by grosser** [comment]
michael@grosser.it

**Comment by rafaelfranca** [comment]
done

**Comment by grosser** [comment]
1.4.0 is out :D

**Pull request merged**
