### PR TITLE
CI: Use ruby 2.4.9, 2.5.7, 2.6.5 and rails 6.0.0

### PR DESCRIPTION
**Pull request by mikong**
Bump the Ruby versions used by Travis CI. Also update from Rails 6.0.0.rc1 to 6.0.0.

### CODE REVIEW

**Comment by mikong** [comment]
The build is failing because it's unable to install rails. sprockets now requires Ruby version >= 2.5.0. Should we drop support for Ruby 2.4.x?

Or use sprockets 3.7.2 instead of 4.0.0?

**Comment by rafaelfranca** [comment]
Lets use sprockets 3.7.

**Comment by mikong** [comment]
Alright. I updated my PR to install sprockets 3.7 under `before_install`. However, that means it's installed for all jobs. Please let me know if sprockets 3.7 should only be installed for Ruby 2.4. I'm not sure what the best way to do that though.

**Comment by byroot** [comment]
Closing as outdated. Thanks for the patch though.

**Pull request closed without merging**
