### PR TITLE
Redirect STDERR to /dev/null during eager_preload

### LINKED ISSUE #396: Spring hangs a lot
We've been having a lot of problems with spring hanging on our systems. I started outputting to a log and here's what I see:

```
[2015-03-19 14:27:01 -0700] [21417] [application:test] initialized -> running
/home/fletch/.rvm/gems/ruby-2.1.5/gems/spring-1.3.3/lib/spring/application.rb:286:in `read': stream closed (IOError)
    from /home/fletch/.rvm/gems/ruby-2.1.5/gems/spring-1.3.3/lib/spring/application.rb:286:in `block (2 levels) in with_pty'
[2015-03-19 14:27:01 -0700] [12838] [application_manager:test] child 21417 shutdown
[2015-03-19 14:27:01 -0700] [21531] [application:test] preloading app
[2015-03-19 14:27:06 -0700] [21531] [application:test] initialized -> running
/home/fletch/.rvm/gems/ruby-2.1.5/gems/spring-1.3.3/lib/spring/application.rb:286:in `read': stream closed (IOError)
    from /home/fletch/.rvm/gems/ruby-2.1.5/gems/spring-1.3.3/lib/spring/application.rb:286:in `block (2 levels) in with_pty'
```

I haven't got a strong idea of what is causing it just yet, though it seems to come up if we change git branches and the like, so maybe some sort of file changes are causing it to just lock up. We have to run `spring stop` and start over.

### PR DESCRIPTION
**Pull request by mvz**
This is a rebased version of #618.

This is a patch by @markiz.

Fixes #396.

### CODE REVIEW

**Comment by mvz** [comment]
I've included the patch from #602 to have a non-failing base build.

**Comment by mvz** [comment]
It looks like the tests are green on modern Rubies and Railses ... If #617 is accepted I can rebase and all should be fine ...

**Comment by mvz** [comment]
I rebased and now the build is green.

**Comment by rafaelfranca** [comment]
Thank you for the pull request. I believe https://github.com/rails/spring/pull/655 fix the same problem. Can you confirm?

**Comment by mvz** [comment]
I'm not sure how to trigger this problem reliably anymore, but I _think_ I was just hit by #396 again with the new spring version 3.1.1 (on Ruby 2.7.4).

**Comment by mvz** [comment]
@markiz since this is your patch, perhaps you can chime in on whether #655 fixes the problem for you?

**Comment by markiz** [comment]
@mvz Hey, apologies about the delay, just looking at the changeset, I'm imagine it's good

**Comment by chrisblatchley** [comment]
hey @mvz i was having the same issue and found this PR. I was investigating this issue myself and arrived on a similar solution then found this PR already open. I tested these changes on our application and it worked great! I ended up making a similar fix that would write to `spring_env.log_file` instead of `/dev/null` but either works. would love to see this get merged!

**Comment by mvz** [comment]
@rafaelfranca thanks for merging this!

**Pull request merged**
