### PR TITLE
speed up tests by not copying bundled directory every time

### PR DESCRIPTION
**Pull request by grosser**
I noticed that the tests run super slow ... because we copy all the gems on every run.

`generator.copy_to(app.root)` takes about 2-3s on my machine,
with this patch it's kept in test/app/gems which makes the copy just take 0.04s

before: 4m33s
after: 2m51s

@rafaelfranca @amatsuda @jonleighton

### CODE REVIEW

**Comment by grosser** [comment]
ok, got that fixed, 1 test was uninstalling spring

**Comment by grosser** [comment]
travis times old:
screen shot 2015-08-01 at 9 29 20 pm

new:
screen shot 2015-08-01 at 9 29 28 pm

**Comment by grosser** [comment]
another commit to kick out a few gems we don't need (sdoc/web-console/byebug), which will decreases first time install time (new users + travis), travis was not impressed, but locally I can see install time drop + runtime of `time rails runner 'puts 1'` decrease by 0.4s

and another to use travis docker infrastructure -> more cpu -> faster builds to gets rid of this warning:
screen shot 2015-08-01 at 10 21 54 pm

also now caches the installed gems (not the apps folder, just the root projects Gemfile) to get rid of these 6s 
image

for the finally runtime of:

image

**Comment by jonleighton** [comment]
Nice work. Happy to merge this when the commented-out tests pass too.

**Comment by grosser** [comment]
ups ... that was leftover debugging, updated :D

**Pull request merged**
