### PR TITLE
fix craches where session pgid is unknown #330

### PR DESCRIPTION
**Pull request by oklas**
This changes make it possible to work on some os.
It contains only pgid result checking and catch exceptions if any.

(more about problem in discussion #330)

### CODE REVIEW

**Comment by oklas** [comment]
@rafaelfranca this does not broke tests and does not add noew feature - this is only fix. Can you please comment or request anything to step to merge?

**Comment by oklas** [comment]
@rafaelfranca Happy new year!

**Comment by oklas** [comment]
Hi @rafaelfranca

This changes actually contains only checking and catch exceptions to make it worked on some os.

Could you review and merge?

**Comment by rafaelfranca** [comment]
Can you confirm this is still a problem with newest release of spring?

**Comment by oklas** [comment]
I can not even confirm problem with one of previous release 2.1.0 - seems it is worked (it can start and stop without crash). It is strange but I think there is no sense to spend time to inspect. The problem was on Freebsd partially because `ps` does not support `-o sess=`. Current version seems does not use such `ps` output. But I notice another minor problem and submit it here #660.

**Pull request closed without merging**
