### PR TITLE
Removing dots in all paragraphs' ends

### PR DESCRIPTION
**Pull request by tjai89**
I have removed all the dots to make the text more balanced. In some places the paragraphs contain dots at the end, in other - do not. I think it's better to make all of them end the same way.

### CODE REVIEW

**Comment by grosser** [comment]
👍 I don't like them either ... but there might be some rails guidelines I don't know about ... @rafaelfranca ?

**Comment by kaspth** [comment]
Our API documentation guide says to follow regular punctuation rules, including periods at the end of sentences.

For instance, Active Record's CHANGELOG does so: https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md

So the inconsistency is the missing periods, not the present ones 😉

**Comment by tjai89** [comment]
So, what is the best option? Remove all dots or add them?

**Comment by matthewd** [comment]
I agree that omitting them can look nice for single-sentence entries. But if there are two sentences, omitting the period on the second just looks weird

Personally, I don't think it's worth bothering to change either way.

**Comment by tjai89** [comment]
I do not want to bother anyone. I will do it myself. Just decide which option is better: leaving dots or removing them, I will do the rest.

**Comment by kaspth** [comment]
Agree with @matthewd, let's just not bother. Thanks!

**Pull request closed without merging**
