### PR TITLE
move gem instead of uninstalling and reinstalling to make test go fro…

### PR DESCRIPTION
**Pull request by grosser**
…m 20s->6s

looking into individual test speed now and this guys was one of the slowest, just moving the gem vs full uninstall+reinstall is a lot faster :)

@jonleighton

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@grosser I have granted commit access to the project so you can commit directly. Feel free to commit and thank you so much for the work.

**Comment by grosser** [comment]
Thx! I'll still make PRs to get feedback :)

**Comment by rafaelfranca** [comment]
Of course.

**Comment by rafaelfranca** [comment]
:shipit:

**Pull request merged**
